---
- name: Service sshd conf
  shell: "echo 'TrustedUserCAKeys /etc/ssh/teleport-user-ca.pub' >> /etc/ssh/sshd_config"

- name: Copy Trusted User CA Keys
  copy:
    src: "{{ role_path }}/files/teleport-user-ca.pub"
    dest: /etc/ssh/teleport-user-ca.pub
    owner: root
    group: root
    mode: '0644'
    
- name: Service sshd restart
  systemd:
    daemon_reload: yes
    name: sshd
    state: restarted

  
  
  