---
- name: Service sshd conf
  shell: "[ \"`grep -c 'TrustedUserCAKeys /etc/ssh/teleport-user-ca.pub' /etc/ssh/sshd_config`\" == \"0\" ] && echo 'TrustedUserCAKeys /etc/ssh/teleport-user-ca.pub' >> /etc/ssh/sshd_config;"
  ignore_errors: yes 

- name: Copy Trusted User CA Keys
  copy:
    src: /tmp/teleport-user-ca.pub
    dest: /etc/ssh/teleport-user-ca.pub
    owner: root
    group: root
    mode: '0644'
    
- name: Service sshd restart
  systemd:
    daemon_reload: yes
    name: sshd
    state: restarted

  
  
  
