---
- name: Export the Teleport CA certificate
  shell: "sudo /usr/local/bin/tctl auth export --type=user > {{ playbook_path }}/roles/import_teleport_certs/filesfilesteleport-user-ca.pub"
  
- name: Allow access for all users
  shell: "sudo sed -e s/cert-authority\ //g -i {{ playbook_path }}/roles/import_teleport_certs/filesfilesteleport-user-ca.pub"
  

