---
- name: Export the Teleport CA certificate
  shell: "/usr/local/bin/tctl auth export --type=user > /tmp/teleport-user-ca.pub"
- name: Allow access for all users
  replace:
    path: /tmp/teleport-user-ca.pub
    regexp: 'cert-authority '
    backup: no 
